import "./style.scss"
import "./scripts/fetch"
import '@fortawesome/fontawesome-free/js/fontawesome'
import '@fortawesome/fontawesome-free/js/solid'
import '@fortawesome/fontawesome-free/js/regular'
import '@fortawesome/fontawesome-free/js/brands'
import "./scripts/fontawsome"
import "./scripts/darkmode"
import "./images/index.png"
import "./scripts/news"
import "./images/diamond.png"